# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_comment_author_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordentry',
            name='word_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_entries', to='dictionary.WordContent'),
        ),
        migrations.AlterField(
            model_name='wordentry',
            name='words_related',
            field=models.ManyToManyField(blank=True, related_name='word_related_to', to='dictionary.WordEntry'),
        ),
    ]
