# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20160228_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
