# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0005_auto_20160228_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_entry_comments', to=settings.AUTH_USER_MODEL)),
                ('word_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_entry_comments', to='dictionary.WordEntry')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='word_entry',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
