# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20160310_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_parent', to='dictionary.Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='location',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='language_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='dictionary.LanguageType'),
        ),
    ]
