# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_auto_20160410_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcontent',
            name='references',
            field=models.ManyToManyField(related_name='words_referenced', to='dictionary.WordContentReference'),
        ),
    ]
