# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 15:35
from __future__ import unicode_literals

import dictionary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_auto_20160428_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='location',
            new_name='location_name',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='file_name',
        ),
        migrations.AddField(
            model_name='language',
            name='location_latitude',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='location_longitude',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(max_length=1024, null=True, upload_to=dictionary.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='wordcontent',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wordcontent',
            name='references',
            field=models.ManyToManyField(related_name='word_contents', to='dictionary.WordContentReference'),
        ),
    ]
