# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-21 12:34
from __future__ import unicode_literals

import dictionary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_auto_20160503_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='image',
            new_name='full',
        ),
        migrations.AddField(
            model_name='picture',
            name='small',
            field=models.ImageField(max_length=1024, null=True, upload_to=dictionary.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='picture',
            name='tinny',
            field=models.ImageField(max_length=1024, null=True, upload_to=dictionary.models.user_directory_path),
        ),
    ]
