# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_auto_20160521_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='location_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='wordcontentreference',
            name='reference',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='wordentry',
            name='short_description',
            field=models.CharField(max_length=1024),
        ),
    ]
